version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    command: uvicorn server.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      MONGO_URI: mongodb://mongo:27017
      STORAGE_PATH: /app/data
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo-data:
